project:
  type: website
  output-dir: docs
  
website:
  title: "test1"
  navbar:
    # logo: images/logo.png
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/max-mascini-562239213/
      - icon: github
        href: https://github.com/maxmascini
    left: 
      - href: index.qmd
        text: Home
  #     - href: about.qmd
  #       text: About me
  # page-footer:
  #   center: 
  #     - text: "About"
  #       href: about.qmd
  #     - text: "License"
  #       href: license.qmd
  #     - text: "Trademark"
  #       href: trademark.qmd
  # favicon: images/logo.png
  comments: false
  # google-analytics:
  # body-header:
  # body-footer:

format:
  html:
    theme: darkly #cosmo #darkly #pulse #skectchy #superhero 
    css: styles.css
  
