project:
  type: website
  output-dir: _site
  resources:
    - files/**

execute: 
  freeze: auto

website:
  title: "MinMaxed"
  # description: "Max Mascini is a "
  bread-crumbs: true
  page-navigation: true
  open-graph: true
  
  # Cookies & Analytics
  google-analytics: 
    tracking-id: "GTM-TJ454JG2"
    anonymize-ip: true
  cookie-consent:
    type: implied
    palette: dark


  # Search Bar
  search: 
    show-item-context: true
    location: navbar
    type: overlay

  navbar:
    # logo: images/logo.png
    collapse-below: lg

    left: 
      - text: "About"
        href: index.qmd

      - text: Blog
        href: blog/blog_index.qmd

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/max-mascini-562239213/

      - icon: github
        href: https://github.com/maxmascini

  page-footer:
    center: 
      - text: "About Site"
        href: about_site.qmd
    left:
      - text: "Copyright 2025, Max Mascini"
  comments: false


format:
  html:
    toc: true
    # theme: darkly #[darkly, theme.scss]
    # theme: styles.scss
    theme: [darkly, styles.scss]
    appearance: false 
    code-copy: true
    code-overflow: wrap
    css: styles.scss
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

